### ISSUE TITLE
在docker中运行报错java.io.IOException: Problem reading font data.

### ISSUE THREAD

**Issue by jiangtao69039** [whvcse/EasyCaptcha#27]
java.io.IOException: Problem reading font data.
	at java.awt.Font.createFont0(Font.java:1000) ~[?:1.8.0_111-internal]
	at java.awt.Font.createFont(Font.java:877) ~[?:1.8.0_111-internal]
	at com.wf.captcha.base.Captcha.setFont(Captcha.java:277) ~[easy-captcha-1.6.2.jar!/:?]
	at com.wf.captcha.base.Captcha.setFont(Captcha.java:273) ~[easy-captcha-1.6.2.jar!/:?]
	at com.wf.captcha.base.Captcha.setFont(Captcha.java:269) ~[easy-captcha-1.6.2.jar!/:?]

docker里没有字体?

**Comment by wltj920** [comment]
我也是一样的错误，用的是Debian Stretch官方容器，顺便把出问题的容器Dockerfile贴出来：

```Dockerfile
FROM debian:stretch
MAINTAINER zhukun

# 指定用户
USER root

WORKDIR /root

# 设置时区
ENV TZ Asia/Shanghai
# 按阿里要求把镜像配置配到文件之前
RUN sed -i '1i\deb http://mirrors.aliyun.com/debian/ stretch main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ stretch main non-free contrib\n\
deb http://mirrors.aliyun.com/debian-security stretch/updates main\n\
deb-src http://mirrors.aliyun.com/debian-security stretch/updates main\n\
deb http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ stretch-updates main non-free contrib\n\
deb http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib\n\
deb-src http://mirrors.aliyun.com/debian/ stretch-backports main non-free contrib' /etc/apt/sources.list \
&& ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo '$TZ' > /etc/timezone

# 更新系统的包管理器中的目录
RUN apt-get update -y

# 设置容器中文，否则中文乱码
ENV LANG C.UTF-8
RUN apt-get install locales -y
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8

# 安装常用工具
RUN apt-get install wget vim gnupg2 -y
# 安装常用网络工具
RUN apt-get install telnet lsof dnsutils traceroute -y
# 安装TrueType字体
RUN apt-get install fonts-dejavu -y

# 安装AdoptOpenJDK
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
RUN echo deb http://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/deb stretch main > /etc/apt/sources.list.d/AdoptOpenJDK.list
RUN apt-get update
RUN apt-get install adoptopenjdk-8-hotspot -y

CMD ["bash"]
```
