### ISSUE TITLE
docker使用openjdk:8-jre-alpine环境的时候缺少字体

### ISSUE THREAD

**Issue by xunkoo** [whvcse/EasyCaptcha#31]
java.lang.NullPointerException
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.GeneratedConstructorAccessor70.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
        at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
        at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
        at com.wf.captcha.GifCaptcha.graphicsImage(GifCaptcha.java:116)
        at com.wf.captcha.GifCaptcha.out(GifCaptcha.java:65)
        at com.wf.captcha.base.Captcha.toBase64(Captcha.java:127)
        at com.wf.captcha.GifCaptcha.toBase64(GifCaptcha.java:85)

**Comment by xunkoo** [comment]
COPY /classes/font/simkai.ttf  /usr/share/fonts/
apk --no-cache add fontconfig
opengJDK 搞定
